[package]
name = "gitflow"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive", "color", "suggestions"] }
clap_complete = "4.6.3"
thiserror = "2.0.18"
anyhow = "1.0.102"
dialoguer = "0.12.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2+spec-1.1.0"
directories = "6.0.0"
which = "8.0.2"
semver = "1.0.28"

[dev-dependencies]
assert_cmd = "2.2.1"
predicates = "3.1.4"
tempfile = "3.27.0"
